apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: weaveclouds.agent.cloud.weave.works
spec:
  group: agent.cloud.weave.works
  names:
    kind: WeaveCloud
    listKind: WeaveCloudList
    plural: weaveclouds
    singular: weavecloud
  scope: Namespaced
  version: v1beta1
